### ISSUE TITLE
Add test for HTML parsing

### ISSUE THREAD

**Issue by marcosnils** [jfrazelle/apk-file#1]
What about adding a test for the HTML parsing in case that the search results page change?.

I was thinking that we can make the test actually hit https://pkgs.alpinelinux.org/contents to retrieve the page but that would require tests to run with a working inet connection. 

Otherwise, we can just hardcode the html so we can test the parsing code. 

Thoughts? 

:smile:

**Comment by jfrazelle** [comment]
So ya I was thinking live pulling but w version changed of packages we can't ensure it won't change but hard doing the results is a good idea :)

**Comment by marcosnils** [comment]
cool, mind if I send a PR?

**Comment by jfrazelle** [comment]
I WAS HOPING YOUD SAY THAT! :D

**Comment by marcosnils** [comment]
on it's way miss.
